spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/spring_boot_test2?useSSL=false
    username: root
    password: root
  mvc:
    throw-exception-if-no-handler-found: true
server:
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
tcc:
  enabled: true
  datasource:
    data-source-provider: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tcc?useSSL=false
    username: root
    password: root
    domain: SAMPLE2
    table-suffix: _SAMPLE2